services:
  - type: web
    name: auth-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/authentication/all
    envVars:
      - key: PORT
        value: 9090
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 86400000
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
